[project]
name = "chitchat"
version = "23.5.0"
requires-python = ">=3.7"
description = "Have a conversation in a new language, at your level."
authors = ["Eric Kalosa-Kenyon <helloateric@gmail.com>"]
license = "MIT"
readme = "README.md"

[project.scripts]
chitchat = "chitchat.main"
