[tool.poetry]
name = "chitchat"
version = "23.5.0"
description = "Have a conversation in a new language, at your level."
authors = ["Eric Kalosa-Kenyon <helloateric@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.30.0"
openai = "^0.27.7"
pyttsx3 = "^2.90"
SpeechRecognition = "^3.10.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
