# Copyright 2023 Eric Kalosa-Kenyon
# Proprietary
#
# This source configures Google App Engine
# Source: https://cloud.google.com/appengine/docs/standard/python3/building-app/writing-web-service

runtime: python310
entrypoint: gunicorn --bind :8080 --workers 1 --threads 8 --timeout 0 --worker-class aiohttp.GunicornWebWorker main:app
# handlers:
# - url: /static
#   static_dir: web/static
# - url: /.*
#   script: auto
