# Copyright 2023 Eric Kalosa-Kenyon
# Proprietary
#
# This source configures Google App Engine
# Source: https://cloud.google.com/appengine/docs/standard/python3/building-app/writing-web-service

runtime: python310
handlers:
  - url: /static
    static_dir: web/static
