name: Test
run-name: ${{ github.actor }} is testing code
on: [pull_request]
jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Setup build environment
        run: mkdir build
      - name: Install test dependencies
        run: pip install '.[tests]'
      - name: Run unit tests
        run: pytest -v -m 'not gcloud and not openai'


